CREATE TABLE product_types (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL UNIQUE,
    description     TEXT
);

CREATE TABLE collections (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(150) NOT NULL UNIQUE,
    description     TEXT
);

CREATE TABLE masters (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_username   VARCHAR(64) UNIQUE,              
    email               VARCHAR(255) UNIQUE NOT NULL,    
    phone               VARCHAR(32) UNIQUE,
    first_name          VARCHAR(100) NOT NULL,
    last_name           VARCHAR(100)
);

CREATE TABLE products (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(255) NOT NULL,
    size                VARCHAR(100),
    weight              INTEGER CHECK (weight >= 0),
    product_type_id     BIGINT NOT NULL,
    collection_id       BIGINT NOT NULL,
    master_id           BIGINT NOT NULL,
    photo_blob          BYTEA,
    description         TEXT,
    material            VARCHAR(150),
    price               NUMERIC(12,2) CHECK (price >= 0),
    stock_qty           INTEGER NOT NULL DEFAULT 0 CHECK (stock_qty >= 0),
    
    CONSTRAINT fk_products_product_type
        FOREIGN KEY (product_type_id)
        REFERENCES product_types(id)
        ON DELETE RESTRICT,
        
    CONSTRAINT fk_products_collection
        FOREIGN KEY (collection_id)
        REFERENCES collections(id)
        ON DELETE RESTRICT,
        
    CONSTRAINT fk_products_master
        FOREIGN KEY (master_id)
        REFERENCES masters(id)
        ON DELETE RESTRICT
);