# Generated by Django 5.1.4 on 2026-03-03 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
                "db_table": "collections",
            },
        ),
        migrations.CreateModel(
            name="Master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_username",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                (
                    "phone",
                    models.CharField(blank=True, max_length=32, null=True, unique=True),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Master",
                "verbose_name_plural": "Masters",
                "db_table": "masters",
            },
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Product Type",
                "verbose_name_plural": "Product Types",
                "db_table": "product_types",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("size", models.CharField(blank=True, max_length=100, null=True)),
                ("weight", models.IntegerField(blank=True, null=True)),
                ("photo_blob", models.BinaryField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("material", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("stock_qty", models.IntegerField(default=0)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.collection",
                    ),
                ),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.master",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.producttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "products",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("weight__gte", 0),
                            ("weight__isnull", True),
                            _connector="OR",
                        ),
                        name="products_weight_gte_0",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("price__gte", 0), ("price__isnull", True), _connector="OR"
                        ),
                        name="products_price_gte_0",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("stock_qty__gte", 0)),
                        name="products_stock_qty_gte_0",
                    ),
                ],
            },
        ),
    ]
